use_frameworks!
platform :ios, '9.0'

target 'AsynchronousSwift_Example' do
  pod 'AsynchronousSwift', :path => '../'
  
  target 'AsynchronousSwift_Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 7.0.2'
  end
end
